### ISSUE TITLE
Breadcrumb blank when page is in a subfolder

### ISSUE THREAD

**Issue by chrisjmccrum** [zHaytam/SmartBreadcrumbs#57] opened 2020-05-31 16:06 UTC
Our razor pages web application is starting to grow so we added subfolders to the Pages directory. So far everything seems to be rendering fine but we're having issues with the last breadcrumb showing blank.

Pages
-> Clients
----> Index.html
Index.html

**Comment by zHaytam** [comment] 2020-05-31 21:02
Hello, I would need a bit more info to try & figure out what's happening, especially how the breadcrumbs are created/configured.

**Comment by chrisjmccrum** [comment] 2020-05-31 21:35
Sure thing - The root index is in the main Pages folder which is where the Default BreadCrumb is defined. Any new pages made in the main Pages folder pick up the BreadCrumb service accordingly. If I make a subfolder in Pages like Clients, the pages in the folder render but the BreadCrumb section only shows the Default BreadCrumb.

The only options I set for the BreadCrumb service is this:
```
            services.AddBreadcrumbs(GetType().Assembly, options =>
            {
                options.TagClasses = "";
                options.OlClasses = "breadcrumb";
                options.LiClasses = "breadcrumb-item";
                options.ActiveLiClasses = "breadcrumb-item active";
            });
```

The Client BreadCrumb is set the default way at the moment
```
    [Breadcrumb]
    public class ClientsIndex : PageModel
```

**Comment by chrisjmccrum** [comment] 2020-06-02 00:27
Is there anything else needed on my end to describe the problem? I would love to use this nifty tool in my project

**Comment by zHaytam** [comment] 2020-06-02 08:37
If you inspect the breadcrumbs part in your website, how many `<li>` elements do you find?

**Comment by chrisjmccrum** [comment] 2020-06-02 17:18
Just one, the Default BreadCrumb

**Comment by zHaytam** [comment] 2020-06-03 10:46
Would it be possible for you to create a small repo that reproduces the issue please?

**Comment by zHaytam** [comment] 2020-07-01 08:40
I'm closing this since it's been a while, feel free to re-open if you still have the issue.

**Closed as completed** 2020-07-01 08:40 UTC
