### ISSUE TITLE
add localizations?

### ISSUE THREAD

**Issue by icesasoftcorp** [zHaytam/SmartBreadcrumbs#41] opened 2019-08-30 22:45 UTC
how can i add Breadcrumb translations?

**Comment by zHaytam** [comment] 2019-09-18 08:52
It is not possible at the moment, PRs are welcome though, it shouldn't be that hard to implement. If I get the time for it I'll do it.

Duplicate of #28

**Closed as completed by zHaytam** 2019-09-18 08:52 UTC

**Comment by markchipman** [comment] 2020-07-31 17:28
One thought I have to accomplish this, although kludgey, would be to have the route for each endpoint have language specific routing (ie "/en/account" vs "/es/cuenta", etc.) and have the breadcrumb use them in conjunction with the correct language translations).

However it seems to me that really, the most direct (.net) way would be to _add an additional optional argument to the breadcrumb attribute_ to pass in the name of the resource resolver.  That way your doing translations using the same key, but getting the correct translated value back.
